CSV Loader implemented but broken
java.lang.NullPointerException: Cannot invoke "modules.Box.getBoxId()" because "box" is null
	at utils.CSVLoader.main(CSVLoader.java:114)